collection_name: sorghum-soybean-primary-2025-01-07-hp-sweep-2025-02-07
entity_name: eberrigan-salk-institute-for-biological-studies
experiment_name: sorghum-soybean-primary-2025-01-07-hp-sweep-2025-02-07
job_type: sweep
project_name: sleap-roots
registry: sleap-roots-models
