collection_name: null
entity_name: eberrigan-salk-institute-for-biological-studies
experiment_name: null
job_type: promote_registry_artifact
project_name: sleap-roots
registry: sleap-roots-models
