collection_name: null
entity_name: eberrigan-salk-institute-for-biological-studies
experiment_name: 20250530_younger_rice_seminal_sweep_input_scaling
job_type: null
project_name: sleap-roots
registry: sleap-roots-models
