collection_name: null
entity_name: eberrigan-salk-institute-for-biological-studies
experiment_name: sorghum-primary-2025-01-06_eval_2025-01-29
job_type: null
project_name: sleap-roots
registry: sleap-roots-models
